import axios from 'axios';

const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000';

const apiClient = axios.create({
    baseURL: API_BASE_URL,
    headers: { 'Content-Type': 'application/json' },
    timeout: 30000,
});

export const predictPower = async (data) => {
    try {
        const response = await apiClient.post('/predict/power', data);
        return response.data;
    } catch (error) {
        console.warn('API call failed, using mock data');
        return { predicted_power: Math.random() * 40 + 10 };
    }
};

export const predictStability = async (data) => {
    try {
        const response = await apiClient.post('/predict/stability', data);
        return response.data;
    } catch (error) {
        console.warn('API call failed, using mock data');
        return {
            stability: Math.random() > 0.35 ? 'stable' : 'unstable',
            instability_percentage: Math.random() * 100
        };
    }
};

export const getInsightsSummary = async () => {
    try {
        const response = await apiClient.get('/insights/summary');
        return response.data;
    } catch (error) {
        console.warn('API call failed, using mock data');
        return {
            total_generation: 18432,
            stability_rate: 34.9,
            peak_generation: 52.3,
            peak_hour: '02:00',
            critical_hours: 847
        };
    }
};

export const generateNarrative = async () => {
    try {
        const response = await apiClient.post('/insights/narrative');
        return response.data;
    } catch (error) {
        console.warn('API call failed, using mock data');
        return {
            narrative: `GRID_OS QUARTERLY ANALYSIS // Q1 2024

EXECUTIVE SUMMARY:
Total generation across Q1 reached 18,432 MW with a capacity factor of 34.3%. Grid stability remained challenging with 65.1% of operational hours classified as unstable, primarily driven by consumption-generation imbalance during evening peak hours.

KEY FINDINGS:
• Peak generation: 52.3 MW recorded at 02:00 hours
• Most unstable period: 19:00 hours (78.3% instability rate)
• Zero generation hours: 25.3% of total operational time
• Average wind speed: 6.96 m/s

NODE PERFORMANCE:
Node 2 (45% allocation) experienced highest stress levels with average consumption of 1.67 MW versus Node 1's 1.24 MW—a 34.7% higher demand load. This imbalance contributed significantly to grid instability patterns.

RECOMMENDATIONS:
1. Implement dynamic load balancing during 18:00-21:00 window
2. Consider energy storage solutions for low-wind periods
3. Optimize Node 2 distribution to reduce stress concentration

SYSTEM STATUS: OPERATIONAL
Generated by GRID_AI // LangChain SQL Agent`
        };
    }
};

export const sendChatMessage = async (data) => {
    try {
        const response = await apiClient.post('/chat', data);
        return response.data;
    } catch (error) {
        console.warn('API call failed, using mock data');
        const { message } = data;

        if (message.toLowerCase().includes('unstable')) {
            return {
                response: "Based on Q1 2024 grid data, peak instability occurs at 19:00 hours with a 78.3% instability rate. This correlates with evening demand surge across all three distribution nodes.",
                sql_query: "SELECT hour, AVG(stability) FROM grid_data WHERE quarter = 1 GROUP BY hour ORDER BY stability DESC LIMIT 1"
            };
        }

        if (message.toLowerCase().includes('compare') || message.toLowerCase().includes('node')) {
            return {
                response: "Node 2 consistently shows higher stress due to its 45% power allocation. Average consumption at Node 2 is 1.67 MW vs Node 1's 1.24 MW, creating a 34.7% higher demand load.",
                sql_query: "SELECT node_id, AVG(consumption) FROM grid_data WHERE quarter = 1 GROUP BY node_id"
            };
        }

        return {
            response: "Based on the grid data analysis, I can help you understand patterns in generation, stability, and node performance. Please ask specific questions about hours, nodes, or time periods.",
            sql_query: "SELECT * FROM grid_data LIMIT 10"
        };
    }
};

export default apiClient;
