"""
Module: merge_wind_data.py
Author: Atharva
Date: 2024
Description: ETL pipeline that merges 20 wind power Excel files (5 years × 4 parameters)
             into a single clean DataFrame with engineered features. Handles the 2019 
             microsecond timestamp quirk, renames columns, performs inner joins, and 
             engineers physics-based features like air density.
Dependencies: pandas, numpy, openpyxl, pathlib
Usage: python -m etl.merge_wind_data
"""

import os
import sys
import numpy as np
import pandas as pd
from pathlib import Path
from typing import Dict, List, Tuple


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

YEARS: List[int] = [2019, 2020, 2021, 2022, 2023]

RAW_DIR: Path = Path(__file__).resolve().parent.parent / "data" / "raw" / "wind_power_data"
PROCESSED_DIR: Path = Path(__file__).resolve().parent.parent / "data" / "processed"

# Mapping: file prefix → original column name in Excel
PARAMETER_MAP: Dict[str, str] = {
    "wind_speed": "Wind speed | (m/s)",
    "air_temperature": "Air temperature | (°C)",
    "pressure": "Pressure | (atm)",
    "power_gen": "Power generated by system | (MW)",
}

# Clean column names after renaming
CLEAN_NAMES: Dict[str, str] = {
    "Wind speed | (m/s)": "wind_speed",
    "Air temperature | (°C)": "temperature",
    "Pressure | (atm)": "pressure",
    "Power generated by system | (MW)": "power_mw",
    "DateTime": "datetime",
}

VALIDATION_FILE: str = "wind_power_gen_3months_validation_data.xlsx"

# Season mapping: month → season code
SEASON_MAP: Dict[int, int] = {
    12: 1, 1: 1, 2: 1,    # Winter
    3: 2, 4: 2, 5: 2,     # Spring
    6: 3, 7: 3, 8: 3,     # Summer
    9: 4, 10: 4, 11: 4,   # Autumn
}


def load_parameter_files(
    parameter_prefix: str,
    column_name: str,
    years: List[int],
    raw_dir: Path,
) -> pd.DataFrame:
    """
    Load and vertically concatenate yearly Excel files for a single parameter.

    Reads one Excel file per year (e.g., wind_speed_2019.xlsx … wind_speed_2023.xlsx),
    rounds DateTime values to the nearest hour to handle the 2019 microsecond quirk,
    and concatenates all years into a single DataFrame.

    Args:
        parameter_prefix (str): File name prefix (e.g., 'wind_speed').
        column_name (str): The original column name inside the Excel file
                           (e.g., 'Wind speed | (m/s)').
        years (List[int]): List of years to load (e.g., [2019, 2020, …, 2023]).
        raw_dir (Path): Path to the directory containing raw Excel files.

    Returns:
        pd.DataFrame: Combined DataFrame with columns ['DateTime', column_name].

    Raises:
        FileNotFoundError: If any expected Excel file is missing.

    Example:
        >>> df = load_parameter_files('wind_speed', 'Wind speed | (m/s)',
        ...                           [2019, 2020], Path('data/raw/wind_power_data'))
        >>> print(df.shape)
        (17518, 2)
    """
    frames: List[pd.DataFrame] = []

    for year in years:
        filename = f"{parameter_prefix}_{year}.xlsx"
        filepath = raw_dir / filename

        if not filepath.exists():
            raise FileNotFoundError(
                f"Expected file not found: {filepath}. "
                f"Please place all wind power Excel files in {raw_dir}"
            )

        df = pd.read_excel(filepath, engine="openpyxl")

        # Handle 2019 microsecond quirk: round to nearest hour
        df["DateTime"] = pd.to_datetime(df["DateTime"]).dt.round("h")

        frames.append(df[["DateTime", column_name]])
        print(f"  📂 Loaded {filename}: {len(df):,} rows")

    combined = pd.concat(frames, ignore_index=True)
    print(f"  ✅ Combined {parameter_prefix}: {len(combined):,} total rows")
    return combined


def merge_all_parameters(
    parameter_dfs: Dict[str, pd.DataFrame],
) -> pd.DataFrame:
    """
    Merge all parameter DataFrames on the 'DateTime' column using inner join.

    Performs sequential inner joins to ensure only rows where ALL four parameters
    have readings are retained. Drops duplicate DateTime columns after merge.

    Args:
        parameter_dfs (Dict[str, pd.DataFrame]): Dictionary mapping parameter names
            to their respective DataFrames, each with a 'DateTime' column.

    Returns:
        pd.DataFrame: Merged DataFrame with DateTime and all parameter columns.

    Raises:
        ValueError: If any DataFrame is missing the 'DateTime' column.

    Example:
        >>> merged = merge_all_parameters({'wind_speed': df_ws, 'temperature': df_temp})
        >>> print(merged.columns.tolist())
        ['DateTime', 'Wind speed | (m/s)', 'Air temperature | (°C)']
    """
    dfs = list(parameter_dfs.values())
    merged = dfs[0]

    for df in dfs[1:]:
        merged = merged.merge(df, on="DateTime", how="inner")

    print(f"✅ Merged all parameters: {merged.shape[0]:,} rows × {merged.shape[1]} columns")
    return merged


def rename_columns(df: pd.DataFrame) -> pd.DataFrame:
    """
    Rename raw Excel column names to clean, snake_case equivalents.

    Maps the original column names (with units and special characters) to
    short, code-friendly names as defined in the CLEAN_NAMES constant.

    Args:
        df (pd.DataFrame): DataFrame with original Excel column names.

    Returns:
        pd.DataFrame: DataFrame with renamed columns.

    Example:
        >>> df = rename_columns(raw_df)
        >>> print(df.columns.tolist())
        ['datetime', 'wind_speed', 'temperature', 'pressure', 'power_mw']
    """
    df = df.rename(columns=CLEAN_NAMES)
    print(f"✅ Renamed columns: {df.columns.tolist()}")
    return df


def engineer_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Engineer additional features from the cleaned wind power DataFrame.

    Creates temporal features (hour, month, season), a physics-based air
    density feature using the ideal gas law, and a binary zero-power indicator.

    The air density formula: ρ = (P × 101325) / (287.05 × (T + 273.15))
    where P is pressure in atm and T is temperature in °C. This is a key
    feature because wind power is proportional to air density.

    Args:
        df (pd.DataFrame): Cleaned DataFrame with columns
            ['datetime', 'wind_speed', 'temperature', 'pressure', 'power_mw'].

    Returns:
        pd.DataFrame: DataFrame with additional engineered feature columns:
            'hour', 'month', 'season', 'air_density', 'is_zero_power'.

    Example:
        >>> df = engineer_features(clean_df)
        >>> print(df[['hour', 'month', 'season', 'air_density']].head())
    """
    # Temporal features
    df["hour"] = df["datetime"].dt.hour
    df["month"] = df["datetime"].dt.month
    df["season"] = df["month"].map(SEASON_MAP)

    # Physics-based feature: air density via ideal gas law
    # ρ = P_pascal / (R_specific × T_kelvin)
    # R_specific for dry air = 287.05 J/(kg·K)
    df["air_density"] = (
        (df["pressure"] * 101325) / (287.05 * (df["temperature"] + 273.15))
    )

    # Binary indicator for zero power generation (insufficient wind)
    df["is_zero_power"] = (df["power_mw"] == 0).astype(int)

    print(f"✅ Engineered features: hour, month, season, air_density, is_zero_power")
    print(f"   Air density range: {df['air_density'].min():.4f} – {df['air_density'].max():.4f} kg/m³")
    print(f"   Zero power hours: {df['is_zero_power'].sum():,} ({df['is_zero_power'].mean()*100:.1f}%)")
    return df


def process_validation_file(raw_dir: Path) -> pd.DataFrame:
    """
    Load and process the 3-month validation dataset (Jan–Mar 2024).

    Applies identical cleaning and feature engineering as the training data:
    column renaming, DateTime rounding, and derived feature computation.

    Args:
        raw_dir (Path): Path to the directory containing the validation Excel file.

    Returns:
        pd.DataFrame: Processed validation DataFrame with all engineered features.

    Raises:
        FileNotFoundError: If the validation file is not found.

    Example:
        >>> val_df = process_validation_file(Path('data/raw/wind_power_data'))
        >>> print(val_df.shape)
        (2184, 10)
    """
    filepath = raw_dir / VALIDATION_FILE

    if not filepath.exists():
        raise FileNotFoundError(
            f"Validation file not found: {filepath}. "
            f"Please place {VALIDATION_FILE} in {raw_dir}"
        )

    df = pd.read_excel(filepath, engine="openpyxl")
    print(f"\n📂 Loaded validation file: {len(df):,} rows")

    # Round DateTime to nearest hour (consistency with training data)
    df["DateTime"] = pd.to_datetime(df["DateTime"]).dt.round("h")

    # Rename columns to clean names
    df = df.rename(columns=CLEAN_NAMES)

    # Engineer the same features as training data
    df = engineer_features(df)

    print(f"✅ Processed validation data: {df.shape[0]:,} rows × {df.shape[1]} columns")
    return df


def run_wind_etl() -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    Execute the complete wind data ETL pipeline.

    Orchestrates the full workflow: loading raw Excel files for each parameter,
    concatenating yearly data, merging all parameters on DateTime, renaming
    columns, engineering features, processing the validation set, and saving
    both datasets as CSV files.

    Returns:
        Tuple[pd.DataFrame, pd.DataFrame]: A tuple of (train_df, validation_df).

    Raises:
        FileNotFoundError: If any required raw data file is missing.

    Example:
        >>> train_df, val_df = run_wind_etl()
        >>> print(f"Train: {train_df.shape}, Validation: {val_df.shape}")
    """
    print("=" * 60)
    print("WIND POWER DATA ETL PIPELINE")
    print("=" * 60)

    # Ensure output directory exists
    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

    # -----------------------------------------------------------------------
    # Step 1: Load each parameter's yearly files and concatenate
    # -----------------------------------------------------------------------
    parameter_dfs: Dict[str, pd.DataFrame] = {}

    for prefix, col_name in PARAMETER_MAP.items():
        print(f"\n--- Loading {prefix} files ---")
        parameter_dfs[prefix] = load_parameter_files(
            parameter_prefix=prefix,
            column_name=col_name,
            years=YEARS,
            raw_dir=RAW_DIR,
        )

    # -----------------------------------------------------------------------
    # Step 2: Merge all parameters on DateTime (inner join)
    # -----------------------------------------------------------------------
    print("\n--- Merging all parameters ---")
    merged_df = merge_all_parameters(parameter_dfs)

    # -----------------------------------------------------------------------
    # Step 3: Rename columns to clean names
    # -----------------------------------------------------------------------
    merged_df = rename_columns(merged_df)

    # -----------------------------------------------------------------------
    # Step 4: Engineer additional features
    # -----------------------------------------------------------------------
    print("\n--- Engineering features ---")
    merged_df = engineer_features(merged_df)

    # -----------------------------------------------------------------------
    # Step 5: Process validation file
    # -----------------------------------------------------------------------
    print("\n--- Processing validation data ---")
    val_df = process_validation_file(RAW_DIR)

    # -----------------------------------------------------------------------
    # Step 6: Save to processed directory
    # -----------------------------------------------------------------------
    train_path = PROCESSED_DIR / "wind_train.csv"
    val_path = PROCESSED_DIR / "wind_validation.csv"

    merged_df.to_csv(train_path, index=False)
    val_df.to_csv(val_path, index=False)

    print(f"\n✅ Saved wind_train.csv: {merged_df.shape[0]:,} rows × {merged_df.shape[1]} columns")
    print(f"✅ Saved wind_validation.csv: {val_df.shape[0]:,} rows × {val_df.shape[1]} columns")
    print(f"📁 Output directory: {PROCESSED_DIR}")
    print("=" * 60)

    return merged_df, val_df


if __name__ == "__main__":
    train_df, val_df = run_wind_etl()
